apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netai-model-pvc
  namespace: netai
  labels:
    app: netai-forecast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-rbd
